# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d40820e6f93e4244fe1e27c546140c7a96e5a1328d34cc7f34f58191b747320900aa07565d8475298e7c444ed40e54b21c985f29ee4526dc4bcb3d26a9f601d

test:
  secret_key_base: 667d74a1a1180a7db39b2160c6be0fcce9236743e5b88161b4f5983e9d1931196d7b3f220f590cf3d5019752ed7b6cf35a010d1609d24d967a80c5c076b106ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
